# defmsg_attributes.py

MSG(ANATOMY_DEX_1,						"very clumsy")
MSG(ANATOMY_DEX_10,						"superhumanly agile")
MSG(ANATOMY_DEX_2,						"somewhat uncoordinated")
MSG(ANATOMY_DEX_3,						"moderately dexterous")
MSG(ANATOMY_DEX_4,						"somewhat agile")
MSG(ANATOMY_DEX_5,						"very agile")
MSG(ANATOMY_DEX_6,						"extremely agile")
MSG(ANATOMY_DEX_7,						"extraordinarily agile")
MSG(ANATOMY_DEX_8,						"like they move like quicksilver")
MSG(ANATOMY_DEX_9,						"like one of the fastest people you have ever seen")
MSG(ANATOMY_MAGIC,						"This is a magical creature")
MSG(ANATOMY_RESULT,						"%s looks %s and %s.")
MSG(ANATOMY_STR_1,						"rather feeble")
MSG(ANATOMY_STR_10,						"superhumanly strong")
MSG(ANATOMY_STR_2,						"somewhat weak")
MSG(ANATOMY_STR_3,						"to be of normal strength")
MSG(ANATOMY_STR_4,						"somewhat strong")
MSG(ANATOMY_STR_5,						"very strong")
MSG(ANATOMY_STR_6,						"extremely strong")
MSG(ANATOMY_STR_7,						"extraordinarily strong")
MSG(ANATOMY_STR_8,						"as strong as an ox")
MSG(ANATOMY_STR_9,						"like one of the strongest people you have ever seen")
MSG(ANIMALLORE_CONJURED,				"like a conjured creature")
MSG(ANIMALLORE_FOOD,					"%s looks %s.")
MSG(ANIMALLORE_FREE,					"%s is %s own master")
MSG(ANIMALLORE_MASTER,					"%s is loyal to %s")
MSG(ANIMALLORE_MASTER_YOU,				"you")
MSG(ANIMALLORE_RESULT,					"%s is a %s")
MSG(ARMSLORE_DAM,						"Attack [%i].")
MSG(ARMSLORE_DEF,						"Defense [%i].")
MSG(ARMSLORE_PSN_1,						"You see no poison.")
MSG(ARMSLORE_PSN_10,					"You see enough poison to kill almost anything.")
MSG(ARMSLORE_PSN_2,						"You detect a tiny amount of poison.")
MSG(ARMSLORE_PSN_3,						"You find a small amount of poison.")
MSG(ARMSLORE_PSN_4,						"You find a little poison.")
MSG(ARMSLORE_PSN_5,						"You find some poison.")
MSG(ARMSLORE_PSN_6,						"There is poison on that.")
MSG(ARMSLORE_PSN_7,						"You find a lot of poison.")
MSG(ARMSLORE_PSN_8,						"You find a large amount of poison.")
MSG(ARMSLORE_PSN_9,						"You find a huge amount of poison.")
MSG(ARMSLORE_REP,						"This item is %s.")
MSG(ARMSLORE_REP_0,						" It looks quite fragile.")
MSG(ARMSLORE_UNABLE,					"That does not appear to be a weapon or armor.")
MSG(AXIS_DENIED,						"Access to Axis' database has been denied!")
MSG(AXIS_FILE_ERROR,					"ERROR: Unable to open Axis' database file")
MSG(AXIS_INFO_ERROR,					"ERROR: Unable to retrieve Axis' database info")
MSG(AXIS_NOT_PRIV,						"This account does not exist or is not privileged to access Axis' database.")
MSG(BEGGING_START,						"You grovel at %s's feet")
MSG(BVBOX_DEPOSITED,					"%d gold was deposited in your account.")
MSG(BVBOX_FULL_ITEMS,					"Your bankbox can't hold more items.")
MSG(BVBOX_FULL_WEIGHT,					"Your bankbox can't hold more weight.")
MSG(BVBOX_OPEN_OTHER,					"%s has %d stones in %s %s")
MSG(BVBOX_OPEN_SELF,					"You have %d stones in your %s")
MSG(CANT_MAKE,							"You can't make that.")
MSG(CANT_MAKE_RES,						"You can't make anything with what you have.")
MSG(CARVE_CORPSE_FEATHERS,				"You pluck the bird. The feathers are now on the corpse.")
MSG(CARVE_CORPSE_HIDES,					"You skin it, and the hides are now in the corpse.")
MSG(CARVE_CORPSE_MEAT,					"You carve some meat, which remains on the corpse.")
MSG(CARVE_CORPSE_NOTHING,				"You see nothing useful to carve from the corpse.")
MSG(CARVE_CORPSE_SCALES,				"You cut away some scales, but they remain on the corpse.")
MSG(CARVE_CORPSE_WOOL,					"You shear it, and the wool is now on the corpse.")
MSG(CMD_INVALID,						"Not a valid command or format")
MSG(CMD_REMOVE_PLAYER,					"Can't remove players this way, Try 'kick' or 'remove 1'")
MSG(CMDAFK_ENTER,						"You go into AFK mode")
MSG(CMDAFK_LEAVE,						"You leave AFK mode")
MSG(COOKING_FIRE_SOURCE,				"You must be near a fire source to cook.")
MSG(COMBAT_ARCH_NOAMMO,					"You have no ammunition.")
MSG(COMBAT_ARCH_TOOCLOSE,				"You are too close.")
MSG(COMBAT_ATTACKO,						"*%s is attacking %s!*")
MSG(COMBAT_ATTACKS,						"*%s is attacking you!*")
MSG(COMBAT_INSIDESHIP,					"You cannot hit characters inside the ship.")
MSG(COMBAT_MISSO,						"%s missed you.")
MSG(COMBAT_MISSS,						"You miss %s.")
MSG(COMBAT_OUTSIDESHIP,					"You cannot hit characters outside the ship.")
MSG(COMBAT_PARRY,						"Your attack was parried!")
MSG(CONT_ITEMS,							" (%d items, %d stones)")
MSG(CONT_FULL_ITEMS,                    "That container cannot hold more items.")
MSG(CONT_FULL_WEIGHT,                   "That container cannot hold more weight.")
MSG(CONT_TOOSMALL,						"The container is too small for that")
MSG(CORPSE_NAME,						"%s of %s")
MSG(DETECTHIDDEN_SUCC,					"You find %s")
MSG(DRINK_CANTMOVE,						"You can't move the item.")
MSG(DRINK_POTION_DELAY,					"You can't drink another potion yet")
MSG(EVALINT_INT_1,						"dumb as a rock")
MSG(EVALINT_INT_10, 					"superhumanly intelligent")
MSG(EVALINT_INT_2,						"fairly stupid")
MSG(EVALINT_INT_3,						"not the brightest")
MSG(EVALINT_INT_4,						"about average")
MSG(EVALINT_INT_5,						"moderately intelligent")
MSG(EVALINT_INT_6,						"very intelligent")
MSG(EVALINT_INT_7,						"like a formidable intellect")
MSG(EVALINT_INT_8,						"extraordinarily intelligent")
MSG(EVALINT_INT_9,						"like a definite genius")
MSG(EVALINT_MAG_1,						"clueless about magic")
MSG(EVALINT_MAG_2,						"to have vague grasp of magic")
MSG(EVALINT_MAG_3,						"capable of using magic")
MSG(EVALINT_MAG_4,						"higly capable with magic")
MSG(EVALINT_MAG_5,						"to be adept of magic")
MSG(EVALINT_MAG_6,						"to have mastery of magic")
MSG(EVALINT_MAN_1,						"nearly absent of mana")
MSG(EVALINT_MAN_2,						"low on mana")
MSG(EVALINT_MAN_3,						"half drained of mana")
MSG(EVALINT_MAN_4,						"have a high charge of mana")
MSG(EVALINT_MAN_5,						"full of mana")
MSG(EVALINT_MAN_6,						"super charged with mana")
MSG(EVALINT_RESULT,						"%s looks %s.")
MSG(EVALINT_RESULT_2,					"They look %s and %s.")
MSG(FISHING_1,							"Try fishing elsewhere")
MSG(FISHING_2,							"There are no fish here.")
MSG(FISHING_3,							"You can't fish from where you are standing.")
MSG(FISHING_4,							"Try fishing in water.")
MSG(FISHING_CLOSE,						"You cannot fish so close to yourself.")
MSG(FISHING_LOS,						"You have no line of sight to that location.")
MSG(FISHING_PROMT,						"Where would you like to fish?")
MSG(FISHING_REACH,						"That is too far away.")
MSG(FISHING_SUCCESS,					"You pull out a %s!")
MSG(FOOD_CANTEAT,						"You are not capable of eating.")
MSG(FOOD_CANTEATF,						"You are simply too full to eat any more!")
MSG(FOOD_CANTMOVE,						"You can't move the item.")
MSG(FOOD_FULL_1,						"You eat the food, but are still extremely hungry.")
MSG(FOOD_FULL_2,						"After eating the food, you feel much less hungry.")
MSG(FOOD_FULL_3,						"You eat the food, and begin to feel more satiated.")
MSG(FOOD_FULL_4,						"You are nearly stuffed, but manage to eat the food.")
MSG(FOOD_FULL_5,						"You feel quite full after consuming the food.")
MSG(FOOD_FULL_6,						"You are stuffed!")
MSG(FOOD_RCANTEAT,						"You can't really eat this.")
MSG(FORENSICS_ALIVE,					"%s is unconscious but alive.")
MSG(FORENSICS_CARVE_1,					"This is the corpse of %s and it has been carved up.")
MSG(FORENSICS_CARVE_2,					"It looks to have been carved by %s")
MSG(FORENSICS_CORPSE,					"Forensics must be used on a corpse.")
MSG(FORENSICS_FAILNAME,					"You cannot determine who killed it")
MSG(FORENSICS_NAME,						"It looks to have been killed by %s")
MSG(FORENSICS_REACH,					"You are too far away to tell much.")
MSG(FORENSICS_TIMER,					"This is %s and it is %lld seconds old. ")
MSG(GMPAGE_PENDING,						"There are %d GM page(s) pending. Use %cPAGE command to view.")
MSG(GMPAGE_PROMPT,						"Please enter a brief description of your problem:")
MSG(GMPAGE_PROMPT_CANCEL,				"Request aborted.")
MSG(GMPAGE_QUEUE,						"Thank you for paging. Queue status : %d")
MSG(GMPAGE_RECEIVED,					"GM page from %s [0%lx] @ %s: %s")
MSG(GMPAGE_SENT,						"The next available Game Master will respond as soon as possible. Please check your Journal for messages every few minutes.")
MSG(GMPAGE_UPDATED,						"Your existing GM page has been updated.")
MSG(GRANDMASTER_MARK,					"%s crafted by %s")
MSG(HEALING_AM,							"Your resurrection attempt is blocked by antimagic.")
MSG(HEALING_ATTEMPT,					"%s is attempting to apply bandages to %s")
MSG(HEALING_ATTEMPTF,					"%s is attempting to apply bandages to %s, but has failed")
MSG(HEALING_BEYOND,						"This creature is beyond help.")
MSG(HEALING_CORPSEG,					"Put the corpse on the ground.")
MSG(HEALING_CURE_1,						"You cure %s of poisons!")
MSG(HEALING_CURE_2,						"%s has cured you of poisons!")
MSG(HEALING_CURE_3,						"You have failed to cure your target!")
MSG(HEALING_CURE_4,						"The attempt to cure you has failed.")		
MSG(HEALING_GHOST,						"You can't heal a ghost! Try healing their corpse.")
MSG(HEALING_HEALTHY,					"You are healthy")
MSG(HEALING_INTERRUPT,					"Your healing was interrupted by the hit!")
MSG(HEALING_NOAIDS,						"Where are your bandages?")
MSG(HEALING_NONCHAR,					"Try healing a creature.")
MSG(HEALING_NONEED,						"%s does not require you to heal or cure them!")
MSG(HEALING_REACH,						"You must be able to reach the target")
MSG(HEALING_RES,						"Resurrect %s")
MSG(HEALING_RES_LOS,                    "The ghost must be in line of sight of its corpse.")
MSG(HEALING_RES_MANIFEST,				"The ghost must manifest to be resurrected.")
MSG(HEALING_RES_TOOFAR,                 "The ghost is too far away from its corpse.")
MSG(HEALING_SELF,						"apply bandages to self")
MSG(HEALING_TO,							"apply bandages to %s")
MSG(HEALING_TOOFAR,						"You are too far away to apply bandages on %s")
MSG(HEALING_WHO,						"you")
MSG(HEALING_WITEM,						"Use a bandage")
MSG(HERDING_LTARG,						"You lost your target!")
MSG(HERDING_NOCROOK,					"You lost your crook!")
MSG(HERDING_SUCCESS,					"The animal goes where it is instructed")
MSG(HIDING_REVEALED,					"You have been revealed")
MSG(HIDING_STUMBLE,						"You stumble apon %s hidden.")
MSG(HIDING_STUMBLE_OSILIKE,				"Being perfectly rested, you shove something invisible out of the way.")
MSG(HIDING_SUCCESS,						"You have hidden yourself well")
MSG(HIDING_TOOLIT,						"You are too well lit to hide")
MSG(INSCRIPTION_FAIL,					"You have no blank scrolls")
MSG(ITEM_CANTDROPTRADE,					"That item cannot be dropped or traded.")
MSG(ITEM_MAGIC,							" It is magical.")
MSG(ITEM_NEWBIE,						" It has a slight magical aura.")
MSG(ITEM_REPAIR,						" It is not repairable.")
MSG(ITEMID_GOLD,						"You estimate %d gold for '%s'")
MSG(ITEMID_MADEOF,						"It is made of ")
MSG(ITEMID_NOVAL,						"The item does not apear to have any real resale value.")
MSG(ITEMID_RESULT,						"That appears to be '%s'.")
MSG(ITEMUSE_ARCHBUTTE_CLEAN,			"You need to remove what is on the target before you can train here.")
MSG(ITEMUSE_ARCHBUTTE_GATHER,			"You gather the arrows and bolts.")
MSG(ITEMUSE_ARCHBUTTE_HIT1,				"hits the outer ring.")
MSG(ITEMUSE_ARCHBUTTE_HIT2,				"hits the middle ring.")
MSG(ITEMUSE_ARCHBUTTE_HIT3,				"hits the inner ring!")
MSG(ITEMUSE_ARCHBUTTE_HIT4,				"hits the bullseye!")
MSG(ITEMUSE_ARCHBUTTE_MISS,				"misses the target altogether.")
MSG(ITEMUSE_ARCHBUTTE_NOAMMO,			"You do not have any arrows with which to practice.")
MSG(ITEMUSE_ARCHBUTTE_RANGED,			"You must practice with ranged weapons on this.")
MSG(ITEMUSE_ARCHBUTTE_SKILL,			"You can't learn any more by using an archery butte.")
MSG(ITEMUSE_ARCHBUTTE_TOOCLOSE,			"You are too close to the target.")
MSG(ITEMUSE_ARCHBUTTE_TOOFAR,			"You are too far away from the archery butte to get an accurate shot.")
MSG(ITEMUSE_ARCHBUTTE_WRONGALIGN,		"You aren't properly lined up with the archery butte to get an accurate shot.")
MSG(ITEMUSE_ARCHBUTTE_WRONGPOS,			"You would do better to stand in front of the archery butte.")
MSG(ITEMUSE_BANDAGE_CLEAN,				"Clean bloody bandages in water")
MSG(ITEMUSE_BANDAGE_PROMT,				"What do you want to use this on?")
MSG(ITEMUSE_BANDAGE_REACH,				"You can't reach this.")
MSG(ITEMUSE_BBOARD_COR,					"Corrupt bboard message")
MSG(ITEMUSE_BBOARD_DEL,					"This board message is not yours")
MSG(ITEMUSE_BBOARD_REACH,				"You can't reach the bboard")
MSG(ITEMUSE_BEDROLL,					"Put this on the ground to open it.")
MSG(ITEMUSE_BEEHIVE,					"The hive appears to be unproductive")
MSG(ITEMUSE_BEEHIVE_STING,				"Ouch! Bee sting!")
MSG(ITEMUSE_BOLT_1,						"You start a new bolt of cloth.")
MSG(ITEMUSE_BOLT_2,						"The bolt of cloth needs a good deal more.")
MSG(ITEMUSE_BOLT_3,						"The bolt of cloth needs a little more.")
MSG(ITEMUSE_BOLT_4,						"The bolt of cloth is nearly finished.")
MSG(ITEMUSE_BOLT_5,						"The bolt of cloth is finished.")
MSG(ITEMUSE_BOOK_FAIL,					"The book apears to be ruined!")
MSG(ITEMUSE_BOW_SHIELD,					"Your shield prevents you from using your bow correctly.")
MSG(ITEMUSE_CANNON_EMPTY,				"Feed shot and powder into the cannon muzzle.")
MSG(ITEMUSE_CANNON_HPOWDER,				"The cannon already has powder.")
MSG(ITEMUSE_CANNON_HSHOT,				"The cannon already has shot.")
MSG(ITEMUSE_CANNON_LPOWDER,				"Powder loaded.")
MSG(ITEMUSE_CANNON_LSHOT,				"Shot loaded.")
MSG(ITEMUSE_CANNON_POWDER,				"The cannon needs powder")
MSG(ITEMUSE_CANNON_SHOT,				"The cannon needs shot")
MSG(ITEMUSE_CANNON_TARG,				"Armed and ready. What is the target?")
MSG(ITEMUSE_CANTTHINK,					"You can't think of a way to use that item.")
MSG(ITEMUSE_CANTMOUNTED,				"You cannot use this while mounted.")
MSG(ITEMUSE_CANTMOUNTEDFLYING,			"You cannot use this while mounted or flying.")
MSG(ITEMUSE_CBALL_PROMT,				"What do you want to use the %s on?")
MSG(ITEMUSE_COTTON_CREATE,				"You create some thread.")
MSG(ITEMUSE_CROOK_PROMT,				"What would you like to herd?")
MSG(ITEMUSE_CROOK_TRY,					"Try just picking up inanimate objects")
MSG(ITEMUSE_CROOK_TARGET,				"Where do you want them to go ?")
MSG(ITEMUSE_DYE_FAIL,					"The dye just drips off this.")
MSG(ITEMUSE_DYE_NOHAIR,					"You have no hair to dye!")
MSG(ITEMUSE_DYE_REACH,					"You must have the item in your backpack or on your person.")
MSG(ITEMUSE_DYE_REACH1,					"You can't reach it.")
MSG(ITEMUSE_DYE_TARG,					"Select the object to use this on.")
MSG(ITEMUSE_DYE_UNABLE,					"You can only use this item on a dye vat.")
MSG(ITEMUSE_DYE_VAT,					"Which dye vat will you use this on?")
MSG(ITEMUSE_FISH_FAIL,					"Use a knife to cut this up")
MSG(ITEMUSE_FISH_UNABLE,				"You can't move this.")
MSG(ITEMUSE_FORGE,						"Select ore to smelt.")
MSG(ITEMUSE_GAMEBOARD_FAIL,				"Can't open game board in a container")
MSG(ITEMUSE_GUILDSTONE_NEW,				"What is the new name?")
MSG(ITEMUSE_HATCH_FAIL,					"You can only open the hatch on board the ship")
MSG(ITEMUSE_JUNK_REACH,					"You can't reach this.")
MSG(ITEMUSE_KEY_FAIL,					"The key must be on your person")
MSG(ITEMUSE_KEY_NOKEY,					"You don't have a key for this.")
MSG(ITEMUSE_KEY_NOLOCK,					"That does not have a lock.")
MSG(ITEMUSE_KEY_PROMT,					"Select item to use the key on.")
MSG(ITEMUSE_KINDLING_CONT,				"You can't light the kindling in a container")
MSG(ITEMUSE_KINDLING_FAIL,				"You fail to ignite the fire.")
MSG(ITEMUSE_LOCKED,						"This item is locked.")
MSG(ITEMUSE_SECURED,					"This item is secured.")
MSG(ITEMUSE_SECURE_ON,					"This item is secure.")
MSG(ITEMUSE_SECURE_OFF,					"This item is no longer secure.")
MSG(ITEMUSE_LOG_UNABLE,					"You can't move this.")
MSG(ITEMUSE_LOG_USE,					"Use a dagger on wood to create bows or shafts.")
MSG(ITEMUSE_LOOM,						"Use thread or yarn on looms")
MSG(ITEMUSE_LOOM_REMOVE,				"You remove the previously uncompleted weave.")
MSG(ITEMUSE_MACEPICK_TARG,				"Where do you want to use the %s?")
MSG(ITEMUSE_MULTI_BLOCKED,				"The structure is blocked.")
MSG(ITEMUSE_MULTI_BUMP,					"Terrain is too bumpy to place structure here.")
MSG(ITEMUSE_MULTI_COLLAPSE,				"The structure collapses.")
MSG(ITEMUSE_MULTI_FAIL,					"No building is allowed here.")
MSG(ITEMUSE_MULTI_INTWAY,				"%s is in your way.")
MSG(ITEMUSE_MULTI_SHIPW,				"The ship would not be completely in the water.")
MSG(ITEMUSE_PICKPOCKET_FAIL,			"You carelessly bump the dip and start it swinging.")
MSG(ITEMUSE_PICKPOCKET_MOUNT,			"You can't practice on this while on a mount.")
MSG(ITEMUSE_PICKPOCKET_SKILL,			"Your ability to steal cannot improve any further by simply practicing on a dummy.")
MSG(ITEMUSE_PICKPOCKET_SUCCESS,			"You successfully avoid disturbing the dip while searching it.")
MSG(ITEMUSE_PICKPOCKET_TOOFAR,			"You are too far away to do that.")
MSG(ITEMUSE_PITCHER_FILL,				"Fill pitcher with some liquid.")
MSG(ITEMUSE_PITCHER_REACH,				"You can't reach this.")
MSG(ITEMUSE_PITCHER_TARG,				"Where do you want to use the %s?")
MSG(ITEMUSE_PORT_LOCKED,				"You can't move the gate.")
MSG(ITEMUSE_POTION_FAIL,				"You can't move the item.")
MSG(ITEMUSE_RUNE_NAME,					"Please enter a description for this marked object.")
MSG(ITEMUSE_SCISSORS_USE,				"Use scissors on hair or cloth to cut")
MSG(ITEMUSE_SEWKIT_PROMT,				"What do you want to use the %s on?")
MSG(ITEMUSE_SEXTANT,					"I am in %s, %s")
MSG(ITEMUSE_SEXTANT_T2A,				"I cannot tell where I'm at.")
MSG(ITEMUSE_SHIPSIDE,					"That is locked")
MSG(ITEMUSE_SHRINE,						"You have a feeling of holiness")
MSG(ITEMUSE_SKIT_UNABLE,				"You can't use a sewing kit on that.")
MSG(ITEMUSE_SPAWN_NEG,					"You negate the spawn.")
MSG(ITEMUSE_SPAWN_RESET,				"You negate the spawn and activate it.")
MSG(ITEMUSE_SPINWHEEL,					"Use wool or cotton on spinning wheels")
MSG(ITEMUSE_SPYGLASS_FE,				"Felucca is in the %s phase.")
MSG(ITEMUSE_SPYGLASS_M1,				"new moon")
MSG(ITEMUSE_SPYGLASS_M2,				"waxing crescent")
MSG(ITEMUSE_SPYGLASS_M3,				"first quarter")
MSG(ITEMUSE_SPYGLASS_M4,				"waxing gibbous")
MSG(ITEMUSE_SPYGLASS_M5,				"full moon")
MSG(ITEMUSE_SPYGLASS_M6,				"waning gibbous")
MSG(ITEMUSE_SPYGLASS_M7,				"third quarter")
MSG(ITEMUSE_SPYGLASS_M8,				"waning crescent")
MSG(ITEMUSE_SPYGLASS_TR,				"Trammel is in the %s phase.")
MSG(ITEMUSE_STEAL,						"You must steal this first.")
MSG(ITEMUSE_SWEB_STUCK,					"You are stuck on the %s")
MSG(ITEMUSE_TRAININGDUMMY_MOUNT,		"You can't practice on this while on a mount.")
MSG(ITEMUSE_TRAININGDUMMY_RANGED,		"You can't practice ranged weapons on this.")
MSG(ITEMUSE_TRAININGDUMMY_SKILL,		"Your skill cannot improve any further by simply practicing with a dummy.")
MSG(ITEMUSE_TRAININGDUMMY_TOOFAR,		"You are too far away to do that.")
MSG(ITEMUSE_TELESCOPE,					"Wow you can see the sky!")
MSG(ITEMUSE_TILLERMAN,					"Arrg stop that.")
MSG(ITEMUSE_TOOFAR,						"Target is too far away")
MSG(ITEMUSE_TRACKER_ATTUNE,				"Who do you want to attune to ?")
MSG(ITEMUSE_TRASHCAN,					"You trash the item. It will decay in 15 seconds.")
MSG(ITEMUSE_UNABLE,						"You can't think of a way to use that item.")
MSG(ITEMUSE_WEAPON_IMMUNE,				"It appears immune to your blow")
MSG(ITEMUSE_WEAPON_PROMT,				"What do you want to use this on?")
MSG(ITEMUSE_WEAPON_WWAIT,				"You must wait for the wool to grow back")
MSG(ITEMUSE_WOOL_CREATE,				"You create some yarn.")
MSG(LOCKPICKING_NOPICK,					"You need a lock pick.")
MSG(LOCKPICKING_PREACH,					"Your pick must be on your person.")
MSG(LOCKPICKING_REACH,					"You can't reach that.")
MSG(LOCKPICKING_WITEM,					"Use the lock pick on a lockable item.")
MSG(LOGIN_LASTLOGGED,					"Last logged: %s")
MSG(LOGIN_PLAYER,						"There is 1 other player here.")
MSG(LOGIN_PLAYERS,						"There are %d other players here.")
MSG(LUMBERJACKING_1,					"Try chopping elsewhere.")
MSG(LUMBERJACKING_2,					"There is nothing here to chop.")
MSG(LUMBERJACKING_3,					"This is not a tree.")
MSG(LUMBERJACKING_4,					"There is no wood left to harvest.")
MSG(LUMBERJACKING_5,					"You hack at the tree and produce some kindling.")
MSG(LUMBERJACKING_6,					"Try chopping a tree.")
MSG(LUMBERJACKING_CLOSE,				"You cannot chop so close to yourself.")
MSG(LUMBERJACKING_LOS,					"You have no line of sight to that location.")
MSG(LUMBERJACKING_REACH,				"That is too far away.")
MSG(LUMBERJACKING_TOOL,					"You must use an axe.")
MSG(MAGERY_1,							"You cannot target an item with this spell.")
MSG(MAGERY_2,							"You cannot target a character with this spell.")
MSG(MAGERY_3,							"You cannot target yourself with this spell.")
MSG(MAGERY_4,							"You must target the ground with this spell.")
MSG(MAGERY_5,							"You have not yet finished preparing the spell.")
MSG(MAGERY_6,							"An anti-magic field disturbs the spell.")
MSG(MAGERY_7,							"You cannot target a player with this spell.")
MSG(MAGERY_8,							"You cannot target an NPC with this spell.")
MSG(MAKESUCCESS_1,						"Due to your poor skill, the item is of shoddy quality")
MSG(MAKESUCCESS_2,						"You were barely able to make this item. It is of poor quality")
MSG(MAKESUCCESS_3,						"You make the item, but it is of below average quality")
MSG(MAKESUCCESS_4,						"The item is of above average quality")
MSG(MAKESUCCESS_5,						"The item is of excellent quality")
MSG(MAKESUCCESS_6,						"Due to your exceptional skill, the item is of superior quality")
MSG(MACRO_OPENDOOR,						"Opening door...")
MSG(MEDITATION_PEACE_1,					"You are at peace.")
MSG(MEDITATION_PEACE_2,					"You are at peace.")
MSG(MEDITATION_TRY,						"You attempt a meditative trance.")
MSG(MINING_1,							"Try mining elsewhere.")
MSG(MINING_2,							"There is nothing here to mine for.")
MSG(MINING_3,							"There is no ore here to mine.")
MSG(MINING_4,							"Try mining in rock!")
MSG(MINING_CANTUSE,						"You can't use the %s where it is.")
MSG(MINING_CLOSE,						"You cannot mine so close to yourself.")
MSG(MINING_CONSUMED,					"It is consumed in the fire.")
MSG(MINING_FIRE,						"The fire is not hot enough to melt this.")
MSG(MINING_FORGE,						"You must be near a forge to smelt")
MSG(MINING_INGOTS,						"Use a smith hammer to make items from ingots.")
MSG(MINING_LOS,							"You have no line of sight to that location")
MSG(MINING_NOT_ORE,						"You need to target the ore you want to smelt")
MSG(MINING_NOTHING,						"You smelt the %s but are left with nothing useful.")
MSG(MINING_REACH,						"That is too far away.")
MSG(MINING_SKILL,						"You lack the skill to smelt %s")
MSG(MINING_TOOL,						"You must use a shovel or pick.")
MSG(MINING_SMELT,						"smelt")
MSG(MSG_ACC_BADPASS,					"Bad password for this account.")
MSG(MSG_ACC_BLOCK,						"Account '%s' blocked")
MSG(MSG_ACC_BLOCKED,					"Account blocked. Send email to admin %s.")
MSG(MSG_ACC_DENIED,						"Sorry, but your access has been denied.")
MSG(MSG_ACC_GUSED,						"All guest accounts are currently used.")
MSG(MSG_ACC_KICK,						"A'%s' was %sed by '%s'")
MSG(MSG_ACC_NEEDPASS,					"Must supply a password.")
MSG(MSG_ACC_PRIV,						"You are not privileged to do that")
MSG(MSG_ACC_UNK,						"Unknown account name '%s'. Try using a 'guest' account.")
MSG(MSG_ACC_WCLI,						"Bad login format. Check Client Version '%s' ?")
MSG(MSG_ACC_PASSCLEAR,					"Password has been cleared.")
MSG(MSG_ACC_PASSCLEAR_RELOG,			"Log out, then back in to set the new password.")
MSG(MSG_ACC_ACCEPTPASS,					"Password has been set.")
MSG(MSG_ACC_INVALIDPASS,				"Invalid password.")
MSG(MSG_ACC_GUESTHIT,					"The guest curse strikes you.")
MSG(MSG_ALREADYONLINE,					"Already online")
MSG(MSG_ARRDEP_1,						"%s has %s %s.")
MSG(MSG_ARRDEP_2,						"arrived in")
MSG(MSG_ARRDEP_3,						"departed from")
MSG(MSG_BOUNCE_PACK,					"in your pack")
MSG(MSG_BOUNCE_CONT,					"in the %s")			
MSG(MSG_CANTPUSH,						"You are not strong enough to push %s out of the way.")
MSG(MSG_CANTSLEEP,						"Can't sleep here")
MSG(MSG_CMD_LACKPRIV,					"You lack privilege to do this.")
MSG(MSG_CORPSE_OF,						"The remains of %s")
MSG(MSG_COWARD_1,						"You have retreated from the battle with %s")
MSG(MSG_COWARD_2,						"%s has retreated from the battle.")
MSG(MSG_EATSOME,						"eat some %s")
MSG(MSG_EMOTE_1,						"*You see %ss %s %s*")
MSG(MSG_EMOTE_2,						"*Your %s %s*")
MSG(MSG_EMOTE_3,						"*You see %ss %s*")
MSG(MSG_EMOTE_4,						"*Your %s*")
MSG(MSG_EMOTE_5,						"*You see %s %s*")
MSG(MSG_EMOTE_6,						"*You %s*")
MSG(MSG_EMOTE_7,						"*You see %s %s*")
MSG(MSG_ERR_INVSET,						"Invalid Set")
MSG(MSG_ERR_NOBLANKRING,				"You can't put blank keys on a keyring.")
MSG(MSG_ERR_NOT4SALE,					"That's not a saleable item.")
MSG(MSG_ERR_NOTGAMEPIECE,				"That is not a game piece")
MSG(MSG_ERR_NOTKEY,						"This is not a key.")
MSG(MSG_EXP_CHANGE_0,					"You have %s %s experience.")
MSG(MSG_EXP_CHANGE_1,					"a bit of")
MSG(MSG_EXP_CHANGE_2,					"a small amount of")
MSG(MSG_EXP_CHANGE_3,					"a little")
MSG(MSG_EXP_CHANGE_4,					"some")
MSG(MSG_EXP_CHANGE_5,					"a moderate amount of")
MSG(MSG_EXP_CHANGE_6,					"alot of")
MSG(MSG_EXP_CHANGE_7,					"large amounts of")
MSG(MSG_EXP_CHANGE_8,					"huge amounts of")
MSG(MSG_EXP_CHANGE_GAIN,				"gained")
MSG(MSG_EXP_CHANGE_LOST,				"lost")
MSG(MSG_EXP_LVLCHANGE_0,				"You have %s a level")
MSG(MSG_EXP_LVLCHANGE_1,				"You have %s some levels")
MSG(MSG_EXP_LVLCHANGE_GAIN,				"gained")
MSG(MSG_EXP_LVLCHANGE_LOST,				"lost")
MSG(MSG_FATIGUE,						"You are too fatigued to move.")
MSG(MSG_FATIGUE_WEIGHT,                 "You are too fatigued to move, because you are carrying too much weight!")
MSG(MSG_FEET,							"at your feet. It is too heavy.")
MSG(MSG_FIGURINE_NOTYOURS,				"This figurine is not yours")
MSG(MSG_FOLLOW_ARROW,					"Follow the Arrow")
MSG(MSG_FOOD_LVL_1,						"starving")
MSG(MSG_FOOD_LVL_2,						"very hungry")
MSG(MSG_FOOD_LVL_3,						"hungry")
MSG(MSG_FOOD_LVL_4,						"fairly content")
MSG(MSG_FOOD_LVL_5,						"content")
MSG(MSG_FOOD_LVL_6,						"fed")
MSG(MSG_FOOD_LVL_7,						"well fed")
MSG(MSG_FOOD_LVL_8,						"stuffed")
MSG(MSG_FOOD_LVL_LOOKS,					"looks %s")
MSG(MSG_FOOD_LVL_OTHER,					"%s looks %s")
MSG(MSG_FOOD_LVL_SELF,					"You are %s")
MSG(MSG_FORGIVEN,						"You have been forgiven")
MSG(MSG_FROZEN,							"You are frozen and can not move.")
MSG(MSG_GUARDS,							"Guards can now be called on you!")
MSG(MSG_GUEST,							"Your guest curse prevents you from taking this action")
MSG(MSG_GUILDRESIGN,					"You cannot quit your %s while in a fight")
MSG(MSG_HEAVY,							"That is too heavy. You can't move that.")
MSG(MSG_HUNGER,							"You are %s")
MSG(MSG_INVIS_OFF,						"Invis OFF")
MSG(MSG_INVIS_ON,						"Invis ON")
MSG(MSG_INVUL_OFF,						"Invulnerability OFF")
MSG(MSG_INVUL_ON,						"Invulnerability ON")
MSG(MSG_IT_IS_DEAD,						"It is dead.")
MSG(MSG_ITEMPLACE,						"You put the %s %s.")
MSG(MSG_JAILED,							"You have been jailed")
MSG(MSG_KARMA_CHANGE,					"Your %s karma is %s")
MSG(MSG_KARMA_CHANGE_1,					"Your %s karma level has %s")
MSG(MSG_KARMA_GAIN,						"gained")
MSG(MSG_KARMA_LOST,						"lost")
MSG(MSG_KARMA_NAME_GOOD,				"good")
MSG(MSG_KARMA_NAME_EVIL,				"evil")
MSG(MSG_KICKED,							"You have been kicked")
MSG(MSG_LOST,							"That %s was lost.")
MSG(MSG_LOST_FOLLOW,					"Lost follow")
MSG(MSG_LOSTMARK,						"That mark was lost.")
MSG(MSG_MAGIC_FEELING,					"You have a strange feeling in your head.")
MSG(MSG_MAGIC_REDUCED,					"Your magical resistance has been reduced.")
MSG(MSG_MANA_EMPTY,						"Your mind is weary.")
MSG(MSG_MANIFEST_NEEDED,				"You must be manifested to perform this action.")
MSG(MSG_MANIFEST_NEEDED_PET,			"You must be manifested for pets to follow your orders.")
MSG(MSG_MANIFEST_SUSC,					"You are susceptible to attack while manifested.")
MSG(MSG_MISPLACED,						"That is too heavy. You can't move that.")
MSG(MSG_NO,								"No.")
MSG(MSG_NO_ACT,							"Action is not possible at this moment")
MSG(MSG_NO_GHOST,						"Your ghost must stay near your body.")
MSG(MSG_NO_NOTHING,						"You cannot do that at the moment")
MSG(MSG_NO_NOTHING_CAST,				"You can't cast spells at the moment")
MSG(MSG_NO_PICKUP,						"You can't pick that up.")
MSG(MSG_NO_PREACH,						"Your pick must be on your person.")
MSG(MSG_NO_REPAIR,						"This item cannot be repaired.")
MSG(MSG_NO_SKILL,						"Not enough skill for this")
MSG(MSG_NO_TRADING,						"Sorry, but no trading")
MSG(MSG_NO_WORK,						"Cannot move object.")
MSG(MSG_NOT_LOADED,						"You do not have any ammunition loaded.")
MSG(MSG_NOT_YOURS,						"This is not yours.")
MSG(MSG_NOW,							"Now %s")
MSG(MSG_NOWFOLLOW,						"Now following %s")
MSG(MSG_NPC_SEX,						"That is a NPC. They don't have a gender.")
MSG(MSG_OBJ_HOLD,						"You are already holding something.")
MSG(MSG_OBJ_WEIGHT,						"It is too heavy.")
MSG(MSG_PET_MOVE,						"The pet is too heavy to move")
MSG(MSG_PET_STONE,						"The pet turns to stone")
MSG(MSG_PET_TAME,						"The pet is now tame")
MSG(MSG_RECALL,							"You can't recall that")
MSG(MSG_RECALL_EQUIP,					"You can't recall that. It is equipped")
MSG(MSG_RECALL_TRAPPED,					"You can't recall that. It is trapped")
MSG(MSG_REDUCED,						"Your magical resistance has been reduced.")
MSG(MSG_REMOVE,							"remove %s")
MSG(MSG_REMOVE_MARK,					"Remove the mark")
MSG(MSG_RIDING,							"You are already riding something.")
MSG(MSG_SALE_SELL,						"%s for sale")
MSG(MSG_SALE_TRADE,						"Trade: %s for %s")
MSG(MSG_SECURITY_NO,					"You cannot secure this.")
MSG(MSG_SECURITY_SET,					"Security set to %s")
MSG(MSG_SOLD,							"That %s was sold.")
MSG(MSG_STANDOFF,						"Stand off")
MSG(MSG_STOLEN,							"%s looks stolen.")
MSG(MSG_THOUART,						"Thou art %s")
MSG(MSG_TOG,							"%s %s %s %s")
MSG(MSG_TRANSFER,						"Transfer %s to %s")
MSG(MSG_WAR,							"War")
MSG(MSG_WEATHER_RAIN,					"The rain has started.")
MSG(MSG_WEATHER_STOP,					"The rain has stopped.")
MSG(MSG_YES,							"Yes.")
MSG(PAUSE_ACCEPT,						"Accepted.")
MSG(PAUSE_CANCEL,						"Cancelled.")
MSG(PAUSE_INVALID,						"Invalid.")
MSG(PAUSE_PROMPT,						"What will you do?")
MSG(PHYSICS_MULTI_BUMP,					"You cannot go there.")
MSG(PHYSICS_MULTI_TOOFAR,				"That is too far away.")
MSG(PHYSICS_ROPE,						"Your rope breaks.")
MSG(PHYSICS_THRU_1,						"You pass through.")
MSG(PHYSICS_THRU_2,						"You cannot go through there.")
MSG(PHYSICS_TOOFAR,						"That is too far away.")
MSG(PHYSICS_WATER,						"You sink.")
MSG(RSTATUS_CANT,						"Cannot use when in combat mode.")
MSG(RSTATUS_LOCK,						"This container is locked.")
MSG(RSTATUS_SECURE,						"This container is secure.")
MSG(RSTATUS_UNSECURE,					"This container is no longer secure.")
MSG(SAYTOOSLOW,							"You speak too slowly.")
MSG(SCORING_GS_A,						"General's %s scores %s %s %s %s")
MSG(SCORING_GS_B,						"%s scored %s %s %s %s %s")
MSG(SCORING_GS_C,						"%s scored %s %s %s %s %s")
MSG(SCORING_GS_D,						"Total points scored %s %s %s %s %s")
MSG(SMELTING_MELT,						"The %s melts in the fire and you lose it.")
MSG(SMELTING_RESULT,					"You get %d %s ingots.")
MSG(SNOOPING_MISSO,						"%s notices your attempt to peek into %s pack.")
MSG(SNOOPING_MISSS,						"You notice %s trying to peek into your pack.")
MSG(SNOOPING_SUCCESS,					"You succesfully peek into %s pack.")
MSG(SNOOPING_TOOFAR,					"You are too far away to peek into %s pack.")
MSG(SOUND_1,							"*sound 0x%0x*")
MSG(SPELL_FAILED,						"You failed the spell.")
MSG(SPELL_SUCCESS,						"You cast the spell.")
MSG(SPIRITSPEAK_1,						"You attempt to channel your spiritual powers.")
MSG(SPIRITSPEAK_2,						"You attempt to channel your spiritual powers.")
MSG(SPIRITSPEAK_3,						"You attempt to channel your spiritual powers.")
MSG(SPIRITSPEAK_4,						"You attempt to channel your spiritual powers.")
MSG(STEALING_ATTEMPT,					"You attempt to steal the %s.")
MSG(STEALING_CANT,						"You can't reach that.")
MSG(STEALING_FAIL,						"You fail to steal the %s.")
MSG(STEALING_OBVIOUS,					"%s tries to steal from %s")
MSG(STEALING_SUCC,						"You successfully steal the %s.")
MSG(STEALING_UNSEEN,					"You succesfully steal the %s unseen.")
MSG(SWIMWEIGHT,                         "You sink because you are carrying too much weight!")
MSG(SWIMWEIGHT_2,                       "You cannot swim with that much weight.")
MSG(TAMING_NOTHING,						"Your target is not an animal.")
MSG(TAMING_SUCCESS,						"You tame the animal.")
MSG(TAMING_TRY,							"You try to tame the animal.")
MSG(TAMING_ATTEMPT,                     "%s attempts to tame the animal.")
MSG(TAMING_TOOWILD,						"The animal is too wild.")
MSG(TAMING_PETS,						"You already have too many pets.")
MSG(TAMING_LOYALTY,						"The pet is loyal to its master.")
MSG(TINKERING_1,						"You need an anvil to make this item.")
MSG(TINKERING_2,						"You need a forge to make this item.")
MSG(TINKERING_3,						"You need a water source to make this item.")
MSG(TINKERING_REACH,					"You are too far away to make that.")
MSG(TINKERING_TOOL,						"You need a tinkering tool.")
MSG(TOOLONGSLEEP,						"You sleep too long and become disoriented.")
MSG(TRADE_COMPLETE,						"Trade complete.")
MSG(TRADE_DEAD,							"You can't trade when dead.")
MSG(TRADE_FAR,							"You can't reach that. You can't trade with someone that far away.")
MSG(TRADE_COMPLETE2,					"Trade complete. You gained %d %s.")
MSG(TRADE_SAME,							"Trade request cancelled. You already own that item.")
MSG(TRADE_REQUEST,						"%s wishes to trade with you.")
MSG(TRADE_TRY,							"Try trading again")
MSG(TRAINING,							"%s will teach you %s for %s gp")
MSG(TRAINING_ANATOMY,					"anatomy")
MSG(TRAINING_ALCHEMY,					"alchemy")
MSG(TRAINING_ANIMALLORE,				"animal lore")
MSG(TRAINING_ARMSLORE,					"arms lore")
MSG(TRAINING_BLACKSMITH,				"blacksmithy")
MSG(TRAINING_BEGGING,					"begging")
MSG(TRAINING_BOWCRAFT,					"bowcraft")
MSG(TRAINING_CARTOGRAPHY,				"cartography")
MSG(TRAINING_COOKING,					"cooking")
MSG(TRAINING_DETECTHIDDEN,				"detect hidden")
MSG(TRAINING_ENTICEMENT,				"enticement")
MSG(TRAINING_EVALINT,					"eval int")
MSG(TRAINING_FENCING,					"fencing")
MSG(TRAINING_FISHING,					"fishing")
MSG(TRAINING_HEALING,					"healing")
MSG(TRAINING_HERDING,					"herding")
MSG(TRAINING_HIDING,					"hiding")
MSG(TRAINING_INSCRIPTION,				"inscription")
MSG(TRAINING_ITEMID,					"item id")
MSG(TRAINING_LUMBERJACKING,				"lumber jacking")
MSG(TRAINING_MAGERY,					"magery")
MSG(TRAINING_MEDITATION,				"meditation")
MSG(TRAINING_MINING,					"mining")
MSG(TRAINING_MUSICIANSHIP,				"musicianship")
MSG(TRAINING_MACEFIGHTING,				"mace fighting")
MSG(TRAINING_POISONING,					"poisoning")
MSG(TRAINING_PROVOCATION,				"provocation")
MSG(TRAINING_RESISTANCE,				"resistance")
MSG(TRAINING_SNOOPING,					"snooping")
MSG(TRAINING_STEALING,					"stealing")
MSG(TRAINING_SWORDSMANSHIP,				"swordsmanship")
MSG(TRAINING_SPIRITSPEAK,				"spirit speak")
MSG(TRAINING_STEALTH,					"stealth")
MSG(TRAINING_TACTICS,					"tactics")
MSG(TRAINING_TAMING,					"taming")
MSG(TRAINING_TINKERING,					"tinkering")
MSG(TRAINING_TAILORING,					"tailoring")
MSG(TRAINING_TRACKING,					"tracking")
MSG(TRAINING_VETERINARY,				"veterinary")
MSG(TRAINING_WRESTLING,					"wrestling")
MSG(TRAPPED,							"You are frozen by the trap!")
MSG(VEND_CONTAINCOST,					"Which container would you like to view the cost of?")
MSG(VEND_FEET,							"at your feet.")
MSG(VEND_PACK,							"in your pack.")
MSG(VEND_BUY_CANTAFFORD,				"You can't afford to buy that!")
MSG(VEND_BUY_NOTHING,					"Nothing bought")
MSG(VEND_BUY_PROMPT,					"Select items you wish to buy")
MSG(VEND_BUY_TOTAL,						"Total cost is %d gp.")
MSG(VEND_CONTPROMPT,					"Which container do you want to purchase?")
MSG(VEND_INVFULL,						"That container cannot hold any more.")
MSG(VEND_INVTOOHEAVY,					"That container cannot hold any more weight.")
MSG(VEND_MAXCHARWEIGHT,					"That would put you overweight.")
MSG(VEND_NOTONHIRE,						"%s will not hire itself out.")
MSG(VEND_NOHAIR,						"You have no hair to cut!")
MSG(VEND_NOTCARRY,						"%s can't carry anything more.")
MSG(VEND_NOTSELL,						"%s can't sell anything more.")
MSG(VEND_NOTYOURS,						"That is not yours to %s.")
MSG(VEND_PRICE,							"Price is %d gp. Continue?")
MSG(VEND_PROMPT,						"Select item you wish to sell")
MSG(VEND_RESNAMES,						"You can't change the name")
MSG(VEND_SELL_CANT,						"Cannot sell that here")
MSG(VEND_SELL_NOTHING,					"Nothing sold")
MSG(VEND_SELL_OWN,						"That is already in your inventory")
MSG(VEND_SELL_TOTAL,					"Total sale is %d gp.")
MSG(VEND_SELL_WORTHLESS,				"That item is worthless.")
MSG(VEND_SUCCESS,						"Transaction successful.")
MSG(VEND_VALUE,							"Value of that item is %d gp.")
MSG(VEND_YPOSSESS,						"You possess %s")
MSG(VENDOR_CANTCARRY,					"The vendor cannot carry anything more.")
MSG(VENDOR_CONTAINER,					"Vendors can only carry containers")
MSG(VENDOR_FEET,						"You dropped %d %s at %s feet.")
MSG(VENDOR_SELL,						"Sell %s for %d gp?")
MSG(VENDOR_HAPPY,						"You feel your contract was well worth it")
MSG(VENDOR_CANCELLED,					"You cancelled the contract with your vendor")
MSG(VENDOR_CONTRACT,					"You contracted with your vendor")
MSG(VENDOR_GIVE,						"Give item to %s")
MSG(VENDOR_HELP,						"The vendor's pack is now visible.")
MSG(VENDOR_LIST,						"Your vendor holds the following items:")
MSG(VENDOR_TOOHEAVY,					"%s is too heavy for %s to carry.")
MSG(VENDOR_VIEW,						"Your vendor holds %d %s.")
MSG(VENDOR_WEIGHT,						"%s would be too heavy for your vendor to carry.")
MSG(VISUAL_FLARE_1,						"flashes and sparks")
MSG(VISUAL_FLARE_2,						"burns brightly")
MSG(VISUAL_FLARE_3,						"flashes violently")
MSG(VISUAL_FLARE_4,						"crackles and sizzles")
MSG(VISUAL_FLARE_5,						"flashes violently")
MSG(VISUAL_FLARE_6,						"burns brightly")
MSG(VISUAL_FLARE_7,						"fizzles and goes out")
MSG(VISUAL_FLARE_8,						"crackles and burns")
MSG(VISUAL_FLARE_9,						"sparks and dies out")
MSG(VISUAL_FLARE_10,					"crackles and sparks")
MSG(VISUAL_FLARE_11,					"crackles and sputters")
MSG(VISUAL_FLARE_12,					"smokes and dies out")
MSG(VISUAL_FLARE_13,					"flashes and burns")
MSG(VISUAL_FLARE_14,					"burns brightly")
MSG(VISUAL_FLARE_15,					"sputters and goes out")
MSG(VISUAL_FLARE_16,					"crackles and sparks")
MSG(VISUAL_FLARE_17,					"burns brightly")
MSG(VISUAL_FLARE_18,					"smokes and goes out")
MSG(VISUAL_FLARE_19,					"fizzles and sparks")
MSG(VISUAL_FLARE_20,					"crackles and dies out")
MSG(WARNING_CHANGE,						"You feel your alignment has changed.")
MSG(WARNING_RED,						"You feel a surge of good fortune as a red sun rises.")
MSG(WARNING_YELLOW,						"You feel a surge of luck as a yellow sun rises.")
MSG(WARNING_BLACK,						"You feel a surge of misfortune as a black sun rises.")
MSG(WARNING_BLUE,						"You feel a surge of misfortune as a blue sun rises.")
MSG(WARNING_GREEN,						"You feel a surge of misfortune as a green sun rises.")
MSG(WARNING_ORANGE,						"You feel a surge of good fortune as an orange sun rises.")
MSG(WARNING_PURPLE,						"You feel a surge of good fortune as a purple sun rises.")
MSG(WARNING_WHITE,						"You feel a surge of luck as a white sun rises.")
MSG(WARNING_YELLOW,						"You feel a surge of luck as a yellow sun rises.")
